### ISSUE TITLE
"noodle" produces 🐩 ("poodle")

### ISSUE THREAD

**Issue by arxanas** [morinted/plover_emoji#10]
The query "noodle" produces the "poodle" emoji 🐩.

There are alternative noodle-related emojis, such as 🍜 ("steaming bowl"/"ramen"). Curiously, "noodles" is listed as an alternative for this emoji at https://emojipedia.org/steaming-bowl/, but it's not found by the emoji plugin.

**Comment by panathea** [comment]
Fixed by aliasing noodle to ramen
